import type { IconType } from 'react-icons'
import {
  SiReact,
  SiTypescript,
  SiNextdotjs,
  SiStyledcomponents,
  SiNodedotjs,
  SiNestjs,
  SiPostgresql,
  SiRedis,
  SiDocker,
  SiGithubactions,
  SiGit,
  SiFigma,
  SiJavascript,
  SiVuedotjs,
  SiMongodb,
  SiGraphql,
  SiTailwindcss,
  SiVercel,
  SiVite,
  SiPrisma,
  SiPython,
  SiFramer,
  SiExpress,
  SiMysql,
  SiSqlite,
  SiFirebase,
  SiLinux,
  SiStorybook,
  SiFlutter,
  SiSentry,
} from 'react-icons/si'
import { LuCode } from 'react-icons/lu'

export const iconMap: Record<string, IconType> = {
  react: SiReact,
  typescript: SiTypescript,
  nextdotjs: SiNextdotjs,
  styledcomponents: SiStyledcomponents,
  nodedotjs: SiNodedotjs,
  nestjs: SiNestjs,
  postgresql: SiPostgresql,
  redis: SiRedis,
  docker: SiDocker,
  githubactions: SiGithubactions,
  git: SiGit,
  figma: SiFigma,
  javascript: SiJavascript,
  vuedotjs: SiVuedotjs,
  mongodb: SiMongodb,
  graphql: SiGraphql,
  tailwindcss: SiTailwindcss,
  vercel: SiVercel,
  vite: SiVite,
  prisma: SiPrisma,
  python: SiPython,
  framer: SiFramer,
  express: SiExpress,
  mysql: SiMysql,
  sqlite: SiSqlite,
  firebase: SiFirebase,
  linux: SiLinux,
  storybook: SiStorybook,
  flutter: SiFlutter,
  sentry: SiSentry,
}

export function getIcon(key: string): IconType {
  return iconMap[key] ?? LuCode
}
